import streamlit as st
import pandas as pd
import sys, os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.analytics import get_kpis, category_performance, top_articles
from src.ai_assistant import generate_editorial_recommendations, generate_headline_suggestions, get_model

st.set_page_config(page_title="AI Assistant", page_icon="💡", layout="wide")

st.markdown("""
<style>
.kpi-card {
    background: linear-gradient(135deg, #1e2130, #252836);
    border-radius: 12px;
    padding: 20px 24px;
    border-left: 4px solid #4CAF50;
    margin-bottom: 8px;
}
.kpi-card.blue   { border-left-color: #2196F3; }
.kpi-card.green  { border-left-color: #4CAF50; }
.kpi-card.orange { border-left-color: #FF9800; }
.kpi-card.purple { border-left-color: #9C27B0; }
.kpi-label {
    font-size: 12px;
    color: #aaa;
    margin-bottom: 6px;
    text-transform: uppercase;
    letter-spacing: 0.8px;
}
.kpi-value {
    font-size: 26px;
    font-weight: 700;
    color: #ffffff;
}
.headline-card {
    background: #1e2130;
    border-radius: 10px;
    padding: 16px 20px;
    border: 1px solid #2a2d3e;
    margin: 8px 0;
    font-size: 15px;
    color: #ffffff;
    border-left: 4px solid #4CAF50;
}
.strategy-card {
    background: #1e2130;
    border-radius: 10px;
    padding: 16px 20px;
    border: 1px solid #2a2d3e;
    margin: 6px 0;
}
.strategy-label {
    font-size: 11px;
    color: #aaa;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-bottom: 6px;
}
.strategy-value {
    font-size: 14px;
    color: #ffffff;
}
.strategy-badge {
    display: inline-block;
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 600;
    margin-bottom: 8px;
}
.badge-star     { background: #1a3a1a; color: #4CAF50; }
.badge-gem      { background: #1a2a3a; color: #2196F3; }
.badge-growth   { background: #3a2a1a; color: #FF9800; }
.badge-warning  { background: #3a1a1a; color: #f44336; }
</style>
""", unsafe_allow_html=True)

@st.cache_data
def load_data():
    return pd.read_csv("data/processed/articles.csv", quoting=1)

df     = load_data()
kpis   = get_kpis(df)
cat_df = category_performance(df)
top_df = top_articles(df, n=10)

# ── Header ──
st.markdown("## 💡 AI Editorial Assistant")
st.caption("Groq LLaMA 3.1 powered content strategy recommendations and headline optimization")

model = get_model()
if model:
    st.success("🟢 Groq API connected — AI-powered recommendations active")
else:
    st.warning("🟡 Groq API not configured — showing rule-based recommendations (fully functional)")

st.divider()

# ── Section 1: Editorial Recommendations ──
col_left, col_right = st.columns([3, 1])

with col_left:
    st.markdown("#### 📋 Editorial Strategy Recommendations")
    st.caption("AI analyzes your platform metrics and generates specific, actionable editorial strategy")

with col_right:
    gen_btn = st.button("Generate recommendations", type="primary", use_container_width=True)

if gen_btn:
    with st.spinner("Analyzing platform metrics and generating recommendations..."):
        result = generate_editorial_recommendations(kpis, cat_df, top_df)

    source_label = "Groq LLaMA 3.1" if result["source"] == "groq" else "Rule-based analytics engine"
    st.caption(f"Generated by: {source_label}")
    st.markdown(result["content"])
else:
    st.markdown("""
    <div class="strategy-card">
        <div class="strategy-label">What you'll get</div>
        <div class="strategy-value">
        Click <b>Generate recommendations</b> to receive AI-powered analysis including:<br><br>
        • Executive summary of platform performance<br>
        • Top 3 growth opportunities specific to your data<br>
        • Underperforming areas with specific fixes<br>
        • Content strategy recommendation for next week<br>
        • The single highest-leverage action to take now
        </div>
    </div>
    """, unsafe_allow_html=True)

st.divider()

# ── Section 2: Headline Generator ──
st.markdown("#### ✍️ AI Headline Generator")
st.caption("Generate 5 optimized headline variants for any topic — designed to maximize engagement and CTR")

col1, col2 = st.columns([3, 1])
with col1:
    topic = st.text_input(
        "Topic or story idea",
        placeholder="e.g. RBI raises interest rates by 50 basis points amid rising inflation"
    )
with col2:
    category = st.selectbox("Category", ["Business", "Sports", "World", "Sci/Tech"])

col3, col4 = st.columns([1, 5])
with col3:
    headline_btn = st.button("Generate headlines", type="primary", use_container_width=True)

if headline_btn:
    if not topic:
        st.warning("Please enter a topic first.")
    else:
        with st.spinner("Generating optimized headlines..."):
            result = generate_headline_suggestions(category, topic, kpis)

        source_label = "Groq LLaMA 3.1" if result["source"] == "groq" else "Rule-based template engine"
        st.caption(f"Generated by: {source_label}")
        st.markdown("**5 optimized headline variants:**")

        for i, headline in enumerate(result["headlines"], 1):
            st.markdown(f'<div class="headline-card">#{i} &nbsp; {headline}</div>', unsafe_allow_html=True)

        st.markdown("")
        st.info("💡 Tip: Take these to the ML Predictor page to score each headline before publishing.")

st.divider()

# ── Section 3: Category Strategy Matrix ──
st.markdown("#### 🎯 Category Strategy Matrix")
st.caption("Data-driven recommendation for where to invest editorial resources")

avg_engagement = cat_df["avg_engagement"].mean()
avg_views      = cat_df["total_views"].mean()

strategy_rows = []
for _, row in cat_df.iterrows():
    if row["avg_engagement"] > avg_engagement and row["total_views"] > avg_views:
        badge   = "⭐ Star"
        css     = "badge-star"
        action  = "Maintain and scale — this category is your engine. Increase publishing frequency."
    elif row["avg_engagement"] > avg_engagement and row["total_views"] <= avg_views:
        badge   = "💎 Hidden Gem"
        css     = "badge-gem"
        action  = "Increase distribution — quality is high but reach is low. Promote more aggressively."
    elif row["avg_engagement"] <= avg_engagement and row["total_views"] > avg_views:
        badge   = "📈 High Reach"
        css     = "badge-growth"
        action  = "Improve content quality — large audience but low engagement. Fix headline strategy."
    else:
        badge   = "⚠️ Needs Attention"
        css     = "badge-warning"
        action  = "Review strategy — both reach and engagement are below average. Reassess content mix."

    strategy_rows.append((row["category"], badge, css, f"{row['avg_engagement']:,.0f}",
                          f"{row['total_views']:,}", action))

cols = st.columns(2)
for i, (cat, badge, css, eng, views, action) in enumerate(strategy_rows):
    with cols[i % 2]:
        st.markdown(f"""
        <div class="strategy-card">
            <span class="strategy-badge {css}">{badge}</span>
            <div style="font-size:16px; font-weight:600; color:#fff; margin-bottom:8px;">{cat}</div>
            <div style="display:flex; gap:24px; margin-bottom:10px;">
                <div><div class="strategy-label">Avg Engagement</div><div class="strategy-value">{eng}</div></div>
                <div><div class="strategy-label">Total Views</div><div class="strategy-value">{views}</div></div>
            </div>
            <div class="strategy-label">Recommended Action</div>
            <div style="font-size:13px; color:#ccc;">{action}</div>
        </div>
        """, unsafe_allow_html=True)

st.divider()

# ── Section 4: Platform snapshot ──
st.markdown("#### 📊 Platform Health Snapshot")
st.caption("Current metrics the AI used to generate recommendations")

c1, c2, c3, c4 = st.columns(4)
with c1:
    st.markdown(f'<div class="kpi-card blue"><div class="kpi-label">Total Articles</div><div class="kpi-value">{kpis["total_articles"]:,}</div></div>', unsafe_allow_html=True)
with c2:
    st.markdown(f'<div class="kpi-card green"><div class="kpi-label">Total Views</div><div class="kpi-value">{kpis["total_views"]/1_000_000:.1f}M</div></div>', unsafe_allow_html=True)
with c3:
    st.markdown(f'<div class="kpi-card orange"><div class="kpi-label">Avg Engagement</div><div class="kpi-value">{kpis["avg_engagement"]:,.0f}</div></div>', unsafe_allow_html=True)
with c4:
    st.markdown(f'<div class="kpi-card purple"><div class="kpi-label">Top Category</div><div class="kpi-value">{kpis["top_category"]}</div></div>', unsafe_allow_html=True)
