import streamlit as st
import pandas as pd
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.analytics import (
    get_kpis,
    category_performance,
    top_articles
)

from src.ai_assistant import (
    generate_editorial_recommendations,
    generate_headline_suggestions,
    get_model
)

st.set_page_config(
    page_title="AI Assistant",
    page_icon="💡",
    layout="wide"
)


@st.cache_data
def load_data():
    return pd.read_csv("data/processed/articles.csv", quoting=1)


df = load_data()

kpis = get_kpis(df)
cat_df = category_performance(df)
top_df = top_articles(df, n=10)

st.title("💡 AI Editorial Assistant")
st.caption("AI-powered content strategy and editorial recommendations")

# --------------------------------------------------
# API Status
# --------------------------------------------------

model = get_model()

if model:
    st.success(
        "🟢 Groq API connected — AI-powered recommendations active"
    )
else:
    st.warning(
        "🟡 Groq API not configured — showing rule-based recommendations"
    )

st.divider()

# --------------------------------------------------
# Editorial Recommendations
# --------------------------------------------------

st.subheader("Editorial Recommendations")

st.write(
    "AI analysis of current content performance with actionable editorial insights."
)

if st.button(
    "Generate Recommendations",
    type="primary"
):
    with st.spinner(
        "Analyzing content performance..."
    ):
        result = generate_editorial_recommendations(
            kpis,
            cat_df,
            top_df
        )

    if result["source"] == "groq":
        st.success("🤖 Generated by Groq AI")
    else:
        st.warning("⚙️ Generated by rule-based analytics engine")

    st.markdown(result["content"])

st.divider()

# --------------------------------------------------
# Headline Generator
# --------------------------------------------------

st.subheader("AI Headline Generator")

st.write(
    "Generate optimized headline variations for any topic to maximize engagement."
)

col1, col2 = st.columns(2)

with col1:
    topic = st.text_input(
        "Topic or story idea",
        placeholder="e.g. RBI raises interest rates by 50 basis points"
    )

with col2:
    category = st.selectbox(
        "Category",
        [
            "Business",
            "Sports",
            "World",
            "Sci/Tech"
        ]
    )

if st.button(
    "Generate Headlines",
    type="primary"
):
    if not topic:
        st.warning(
            "Please enter a topic first."
        )
    else:
        with st.spinner(
            "Generating optimized headlines..."
        ):
            result = generate_headline_suggestions(
                category,
                topic,
                kpis
            )

        if result["source"] == "groq":
            st.success("🤖 Generated by Groq AI")
        else:
            st.warning("⚙️ Generated by rule-based template engine")

        st.subheader("Suggested Headlines")

        for i, headline in enumerate(
            result["headlines"],
            start=1
        ):
            col_h, col_btn = st.columns([5, 1])

            with col_h:
                st.write(
                    f"**{i}.** {headline}"
                )

            with col_btn:
                st.button(
                    "Analyze",
                    key=f"analyze_{i}"
                )

st.divider()

# --------------------------------------------------
# Platform Health Snapshot
# --------------------------------------------------

st.subheader("Platform Health Snapshot")

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "Total Articles",
    f"{kpis['total_articles']:,}"
)

c2.metric(
    "Total Views",
    f"{kpis['total_views']:,}"
)

c3.metric(
    "Avg Engagement",
    f"{kpis['avg_engagement']:,.0f}"
)

c4.metric(
    "Top Category",
    kpis["top_category"]
)

st.divider()

# --------------------------------------------------
# Category Strategy Matrix
# --------------------------------------------------

st.subheader("Category Strategy Matrix")

st.caption(
    "Use this to decide where to invest editorial resources."
)

strategy_rows = []

avg_engagement = cat_df["avg_engagement"].mean()
avg_views = cat_df["total_views"].mean()

for _, row in cat_df.iterrows():

    eng_vs_avg = (
        "Above Avg"
        if row["avg_engagement"] > avg_engagement
        else "Below Avg"
    )

    views_vs_avg = (
        "High Volume"
        if row["total_views"] > avg_views
        else "Low Volume"
    )

    if (
        row["avg_engagement"] > avg_engagement
        and row["total_views"] > avg_views
    ):
        strategy = "⭐ Star — Maintain and Scale"

    elif (
        row["avg_engagement"] > avg_engagement
        and row["total_views"] <= avg_views
    ):
        strategy = "💎 Hidden Gem — Increase Distribution"

    elif (
        row["avg_engagement"] <= avg_engagement
        and row["total_views"] > avg_views
    ):
        strategy = "📈 High Reach — Improve Content Quality"

    else:
        strategy = "⚠️ Needs Attention — Review Strategy"

    strategy_rows.append(
        {
            "Category": row["category"],
            "Avg Engagement": f"{row['avg_engagement']:,.0f}",
            "Total Views": f"{row['total_views']:,}",
            "Engagement": eng_vs_avg,
            "Volume": views_vs_avg,
            "Strategy": strategy,
        }
    )

strategy_df = pd.DataFrame(
    strategy_rows
)

st.dataframe(
    strategy_df,
    hide_index=True,
    use_container_width=True
)