import pandas as pd
import numpy as np
from datetime import datetime
import os


class NewsFlowReport:
    pass


def safe_text(text):
    return (
        str(text)
        .replace("—", "-")
        .replace("–", "-")
        .replace("•", "*")
        .replace("’", "'")
        .replace("‘", "'")
        .replace("“", '"')
        .replace("”", '"')
    )


def generate_report(df, output_path="reports/weekly_report.pdf"):
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("fpdf2 not installed. Run: pip install fpdf2")

    os.makedirs("reports", exist_ok=True)

    from src.analytics import get_kpis, category_performance, top_articles

    kpis = get_kpis(df)
    cat_df = category_performance(df)
    top_df = top_articles(df, n=5)

    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(30, 30, 30)

            self.cell(
                0,
                10,
                "NewsFlow Analytics",
                new_x="LMARGIN",
                new_y="NEXT"
            )

            self.set_font("Helvetica", "", 9)
            self.set_text_color(120, 120, 120)

            self.cell(
                0,
                6,
                "Media Traffic Intelligence Platform - Automated Weekly Report",
                new_x="LMARGIN",
                new_y="NEXT"
            )

            self.set_draw_color(200, 200, 200)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(150, 150, 150)

            footer_text = (
                f"Generated by NewsFlow Analytics | "
                f"{datetime.now().strftime('%Y-%m-%d %H:%M')} | "
                f"Page {self.page_no()}"
            )

            self.cell(
                0,
                10,
                safe_text(footer_text),
                align="C"
            )

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --------------------------------------------------
    # Report Metadata
    # --------------------------------------------------

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 30)

    pdf.cell(
        0,
        7,
        safe_text(
            f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}"
        ),
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.ln(4)

    # --------------------------------------------------
    # Executive Summary
    # --------------------------------------------------

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 100, 180)

    pdf.cell(
        0,
        8,
        "Executive Summary - Key Performance Indicators",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_draw_color(30, 100, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())

    pdf.ln(3)
    pdf.set_text_color(30, 30, 30)

    kpi_data = [
        ("Total Articles Analyzed", f"{kpis['total_articles']:,}"),
        ("Total Views", f"{kpis['total_views']:,}"),
        ("Average Engagement Score", f"{kpis['avg_engagement']:,.0f}"),
        ("Total Shares", f"{kpis['total_shares']:,}"),
        ("Average Views per Article", f"{kpis['avg_views']:,}"),
        ("Top Performing Category", kpis["top_category"]),
        ("Top Performing Author", kpis["top_author"]),
        ("Articles This Week", f"{kpis['articles_this_week']:,}")
    ]

    for label, value in kpi_data:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(80, 7, safe_text(label + ":"))

        pdf.set_font("Helvetica", "", 10)
        pdf.cell(
            0,
            7,
            safe_text(value),
            new_x="LMARGIN",
            new_y="NEXT"
        )

    pdf.ln(4)

    # --------------------------------------------------
    # Category Performance
    # --------------------------------------------------

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 100, 180)

    pdf.cell(
        0,
        8,
        "Category Performance Breakdown",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_draw_color(30, 100, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())

    pdf.ln(3)
    pdf.set_text_color(30, 30, 30)

    col_widths = [40, 35, 38, 38, 39]

    headers = [
        "Category",
        "Articles",
        "Avg Engagement",
        "Total Views",
        "Total Shares"
    ]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 248, 255)

    for i, h in enumerate(headers):
        pdf.cell(
            col_widths[i],
            7,
            safe_text(h),
            border=1,
            fill=True
        )

    pdf.ln()

    pdf.set_font("Helvetica", "", 9)

    for _, row in cat_df.iterrows():
        pdf.cell(col_widths[0], 6, safe_text(row["category"]), border=1)
        pdf.cell(col_widths[1], 6, str(row["article_count"]), border=1)
        pdf.cell(col_widths[2], 6, f"{row['avg_engagement']:,.0f}", border=1)
        pdf.cell(col_widths[3], 6, f"{row['total_views']:,}", border=1)
        pdf.cell(col_widths[4], 6, f"{row['total_shares']:,}", border=1)
        pdf.ln()

    pdf.ln(4)

    # --------------------------------------------------
    # Top Articles
    # --------------------------------------------------

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 100, 180)

    pdf.cell(
        0,
        8,
        "Top 5 Articles by Engagement",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_draw_color(30, 100, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())

    pdf.ln(3)
    pdf.set_text_color(30, 30, 30)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 248, 255)

    pdf.cell(95, 7, "Title", border=1, fill=True)
    pdf.cell(30, 7, "Category", border=1, fill=True)
    pdf.cell(35, 7, "Engagement", border=1, fill=True)
    pdf.cell(30, 7, "Views", border=1, fill=True)

    pdf.ln()

    pdf.set_font("Helvetica", "", 8)

    for _, row in top_df.iterrows():
        title = str(row["title"])

        if len(title) > 52:
            title = title[:52] + "..."

        pdf.cell(95, 6, safe_text(title), border=1)
        pdf.cell(30, 6, safe_text(row["category"]), border=1)
        pdf.cell(35, 6, f"{row['engagement_score']:,.0f}", border=1)
        pdf.cell(30, 6, f"{row['views']:,}", border=1)

        pdf.ln()

    pdf.ln(4)

    # --------------------------------------------------
    # Recommendations
    # --------------------------------------------------

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 100, 180)

    pdf.cell(
        0,
        8,
        "Editorial Recommendations",
        new_x="LMARGIN",
        new_y="NEXT"
    )

    pdf.set_draw_color(30, 100, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())

    pdf.ln(3)
    pdf.set_text_color(30, 30, 30)

    sorted_cat = cat_df.sort_values(
        "avg_engagement",
        ascending=False
    )

    bottom_cat = sorted_cat.iloc[-1]["category"]
    top_cat = kpis["top_category"]

    recs = [
        f"1. SCALE {top_cat.upper()} CONTENT: Highest engagement category. Increase publishing frequency by 20%.",
        f"2. IMPROVE {bottom_cat.upper()} HEADLINES: Bottom performing category. Test numbers and power words.",
        f"3. AUTHOR LEVERAGE: {kpis['top_author']} is the top performer. Increase assignment volume.",
        f"4. ENGAGEMENT TARGET: Improve average engagement by 10 percent through headline optimization.",
        f"5. DISTRIBUTION: Strengthen social media amplification for underperforming categories."
    ]

    pdf.set_font("Helvetica", "", 10)

    for rec in recs:
        pdf.multi_cell(
            0,
            6,
            safe_text(rec)
        )
        pdf.ln(2)

    pdf.output(output_path)

    print(f"Report saved to {output_path}")

    return output_path